### ISSUE TITLE
Android: Delete ARMv6 libs and include files?

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp-ffmpeg#24]
Since we dropped support for older versions of Android, and IIRC ARMv6 has crashing issues with GCC 4.8 on PPSSPP, is it time to delete the ARMv6 FFMPEG stuff too, under Android?

**Comment by mrcmunir** [comment]
I think https://github.com/hrydgard/ppsspp-ffmpeg/commit/ccb64015646013263f20ee3d87ca0d6481677ccf 

Closed this issue .
