### ISSUE TITLE
Compilation under arm64

### ISSUE THREAD

**Issue by Shatur** [hrydgard/ppsspp-ffmpeg#69]
We currently have [linux_arm64.sh](https://github.com/hrydgard/ppsspp-ffmpeg/blob/master/linux_arm64.sh), but it's used for cross-compilation. But sometimes it's needed to build the project on arm64 device directly.
Could you provide an option or a separate script for it?

**Comment by Shatur** [comment]
[Here](https://pastebin.com/raw/nTz96K9g) is the script I currently use.

**Comment by hrydgard** [comment]
Thanks, I'm happy to include that. Would you like to make a PR yourself to get the "credit", or should I just throw it in there?

**Comment by Shatur** [comment]
@hrydgard I'm not the author of the script, I took it from https://github.com/hrydgard/ppsspp/issues/17447#issuecomment-1575498162.
And the author said to submit the issue here. So it probably would be better if you remove the commented out code from the script and include it.

**Comment by hrydgard** [comment]
Ah, I see. Okay, I'll include it.

**Comment by hrydgard** [comment]
Done.
